import pandas as pd
import os

AGG_RULES = {
    'Površina območja (km2)': ("sum", None),
    'Število prebivalcev (H2/2024)': ("sum", None),
    'Povprečna starost prebivalcev': ("wmean", 'Število prebivalcev (H2/2024)'),
    'Naravni prirast /1000 prebival.': ("wmean", 'Število prebivalcev (H2/2024)'),
    'Prenočitve turistov SKUPAJ': ("sum", None),
    'Prenočitve turistov Domači': ("sum", None),
    'Prenočitve turistov\tTuji': ("sum", None),
    'Delež tujih prenočitev': ("wmean", 'Prenočitve turistov SKUPAJ'),
    'Prihodi turistov SKUPAJ': ("sum", None),
    'Prihodi turistov Domači': ("sum", None),
    'Prihodi turistov Tuji': ("sum", None),
    'PDB turistov\tSKUPAJ': ("wmean", 'Prihodi turistov SKUPAJ'),
    'PDB turistov\tDomači': ("wmean", 'Prihodi turistov Domaći'),
    'PDB turistov\tTuji': ("wmean", 'Prihodi turistov Tuji'),
    'Nastanitvene kapacitete - Nedeljive enote': ("sum", None),
    'Nastanitvene kapacitete - vsa ležišča': ("sum", None),
    'Nastanitvene kapacitete - stalna ležišča': ("sum", None),
    'Struktura nastanitvenih kapacitet - Sobe (nedeljive enote)\t- Hoteli in podobni obrati': ("sum", None),
    'Struktura nastanitvenih kapacitet - Sobe (nedeljive enote)\t- Kampi': ("sum", None),
    'Struktura nastanitvenih kapacitet - Sobe (nedeljive enote) - Druge vrste kapacitet': ("sum", None),
    'Struktura nastanitvenih kapacitet - Stalna ležišča - Hoteli in podobni obrati': ("sum", None),
    'Struktura nastanitvenih kapacitet - Stalna ležišča - Kampi': ("sum", None),
    'Struktura nastanitvenih kapacitet - Stalna ležišča - Druge vrste kapacitet': ("sum", None),
    'Delež stalnih ležišč v Hotelih ipd.': ("wmean", 'Nastanitvene kapacitete - stalna ležišča'),
    'Povprečna letna zasedenost staln. ležišč': ("wmean", 'Nastanitvene kapacitete - stalna ležišča'),
    'Ocenjena povp. Letna zased. sob (nedeljivih enot)': ("wmean", 'Nastanitvene kapacitete - Nedeljive enote'),
    'Pritisk turizma na družbeni prostor': ("wmean", 'Število prebivalcev (H2/2024)'),
    'Gostota turizma': ("wmean", 'Površina območja (km2)'),
    "Intenzivnost turizma": ("wmean", "Število prebivalcev (H2/2024)"),
    "Delovno aktivni v  turizmu (OECD/WTO)": ("sum", None),
    "Število zaposl. in samozaposl. v aktivnih podjetjih v Gostinstvu (I)": ("sum", None),
    "Zaposleni v Gostinstvu (I) v registr.podjetjih in s.p.": ("sum", None),
    " Zaposleni v nastan.dejav. (I55) v registr.podjetjih in s.p.": ("sum", None),
    "Vsi delovni aktivni na območju": ("sum", None),
    "Delež delovno aktivnih v turizmu (OECD/WTO)": ("wmean", "Vsi delovni aktivni na območju"),
    "Število vseh vrst podjetij na območju": ("sum", None),
    "Prihodek (v 1000 EUR) vseh podjetij na območju": ("sum", None),
    "Število reg. podjetij in s.p.  v Gostinstvu (I)": ("sum", None),
    "Prihodki reg.podjetij in s.p. v Gostinstvu (I)": ("sum", None),
    "Dodana vrednost reg.podjetij v Gostinstvu (I)": ("sum", None),
    "Dodana vrednost/zaposl. reg.podjetij Gostinstvu (I)": ("wmean", "Zaposleni v Gostinstvu (I) v registr.podjetjih in s.p."),
    "Ocenjeni stroški dela v reg. podj. v Gostinski (I) dejavnosti": ("sum", None),
    "Stroški dela na zaposl. na leto v reg. podj. v Gostinski (I) dejavnosti": ("wmean", "Zaposleni v Gostinstvu (I) v registr.podjetjih in s.p."),
    "Delež stroškov dela v prihodkih v reg. podj. v Gostinstvu (I)": ("wmean", "Prihodki reg.podjetij in s.p. v Gostinstvu (I)"),
    "Delež stroškov dela v dod vredn. v reg. podj. v Gostinstvu (I)": ("wmean", "Dodana vrednost reg.podjetij v Gostinstvu (I)"),
    "EBITDA v reg.podjetjih in s.p. v Gostinstvu (I)": ("sum", None),
    "EBITDA marža v reg.podjetjih in s.p. v Gostinstvu (I)": ("wmean", "Prihodki reg.podjetij in s.p. v Gostinstvu (I)"),
    "Čisti dobiček/izguba v reg. podj. in s.p. v Gostinstvu (I)": ("sum", None),
    "Sredstva v reg. Podjetjih in s.p. v Gostinstvu (I)": ("sum", None),
    "Kapital v reg. Podjetjih in s.p. v Gostinstvu (I)": ("sum", None),
    "Donosnost sredstev v reg. podjetjih in s.p. v Gostinstvu (I)": ("wmean", "Sredstva v reg. Podjetjih in s.p. v Gostinstvu (I)"),
    "Donosnost kapitala v reg. podjetjih in s.p. v Gostinstvu (I)": ("wmean", "Kapital v reg. Podjetjih in s.p. v Gostinstvu (I)"),
    "Dobičkovnost prihodkov v podjetjih in s.p. v Gostinstvu (I)": ("wmean", "Prihodki reg.podjetij in s.p. v Gostinstvu (I)"),
    "Število reg. podjetij in s.p. v nastanitveni dejav. (I 55)": ("sum", None),
    "Prihodki reg.podjetij in s.p. v nastanitveni dejav. (I 55)": ("sum", None),
    "Dodana vrednost reg.podjetij v nastanitveni dejav. (I 55)": ("sum", None),
    "Dodana vrednost/zaposl. V reg.podjetjih v nast.dejav. (I 55)": ("wmean", " Zaposleni v nastan.dejav. (I55) v registr.podjetjih in s.p."),
    "Ocenjeni stroški dela v reg. podj. v nastan.gost. (I 55) dejavnosti": ("sum", None),
    "Stroški dela na zaposl. na leto v reg. podj. v nast.gost. (I 55) dejavnosti": ("wmean", " Zaposleni v nastan.dejav. (I55) v registr.podjetjih in s.p."),
    "Delež stroškov dela v prihodkih v reg. podj. v nast.gost.dej. (I 55)": ("wmean", "Prihodki reg.podjetij in s.p. v nastanitveni dejav. (I 55)"),
    "Delež stroškov dela v dod vredn. v reg. podj. v nast.gost.dej. (I)": ("wmean", "Dodana vrednost reg.podjetij v nastanitveni dejav. (I 55)"),
    "EBITDA v reg.podjetjih in s.p. v nastanitveni dejav. (I 55)": ("sum", None),
    "EBITDA marža v reg.podjetjih v nastanitveni dejav. (I 55)": ("wmean", "Prihodki reg.podjetij in s.p. v nastanitveni dejav. (I 55)"),
    "Čisti dobiček/izguba v reg. podj. v nastanitveni dejav. (I 55)": ("sum", None),
    "Sredstva v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)": ("sum", None),
    "Kapital v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)": ("sum", None),
    "Donosnost sredstev v nastanitveni dejav. (I 55)": ("wmean", "Sredstva v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)"),
    "Donosnost kapitala v nastanitveni dejav. (I 55)": ("wmean", "Kapital v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)"),
    "Dobičkovnost prihodkov v nastanitveni dejav. (I 55)": ("wmean", "Prihodki reg.podjetij in s.p. v nastanitveni dejav. (I 55)"),
    "Cel.prihodki v nastan. dejav. na prenočitev": ("wmean", "Prenočitve turistov SKUPAJ"),
    "Ocenjeni.prihodki iz nast. dejav. na prenočitev": ("wmean", "Prenočitve turistov SKUPAJ"),
    "Ocenj.prihodki iz nastan. dej. na razpoložljivo sobo (enoto)": ("wmean", "Prenočitve turistov SKUPAJ"),
    "Ocenjeni prihodki iz nast.dej. na prodano sobo (ned.enoto)": ("wmean", "Prenočitve turistov SKUPAJ"),
    "Poraba el.energije (MWh) Dejavnost Gostinstvo (I)": ("sum", None),
    "Poraba el.energ. v kWh na realiz. 1000 EUR prihodka v Gostinstvu (I)": ("wmean", "Poraba el.energije (MWh) Dejavnost Gostinstvo (I)"),
    "Število kmetijskih  gospodarstev": ("sum", None),
    "Ocena skupne ekonomske velikosti kmetij.gospodarstev": ("sum", None),
    "Skupaj neto prejeti dohodek povp. na prebivalca": ("wmean", "Število prebivalcev (H2/2024)"),
    "Neto prejeti dohodek iz dela, povp. na preb.": ("wmean", "Število prebivalcev (H2/2024)"),
    "Neto prejeti dohodek iz premoženja, kapitala, idr.povp. na preb.": ("wmean", "Število prebivalcev (H2/2024)"),
    "Povprečna mesečna neto  plača/zaposl. osebo (EUR)": ("wmean", "Število prebivalcev (H2/2024)"),
    "Povprečna neto plača izplačana na zaposl. osebo v Gostinstvu (I)": ("wmean", "Število prebivalcev (H2/2024)"),
    " Indeks neto plača v Gostinstvu (I) /pvp. plača v vseh dejavnostih": ("mean", None),
    "Število izdanih gradbenih dovoljenj/1000 prebivalcev": ("wmean", "Število prebivalcev (H2/2024)"),
    " Število počitniških stanovanj": ("sum", None),
    "Delež naseljenih stanovanj od vseh razp.": ("mean", None),
    "Komunalni odpadki, zbrani  z javnim odvozom (kg/prebivalca)": ("wmean", "Število prebivalcev (H2/2024)"),
    "Štev.dijakov in študentov višjih strok. in visokošolsk.progr./1000 preb.": ("wmean", "Število prebivalcev (H2/2024)"),
}

df_data = pd.read_excel("/Users/peter/Desktop/Slovenija/Razširjeni kazalniki/streamlit_turisticne_regije_app_v4/Skupna tabela občine.xlsx")

df_mapping = pd.read_excel("/Users/peter/Desktop/mapping.xlsx")

list_data = list(df_data.columns)

list_mapping = df_mapping["indikator"].to_list()


for i in list_data:
    print(i)


