APP_TITLE = "Upravljanje turističnih destinacij Slovenije"
APP_KICKER = "Interaktivna aplikacija"
APP_SUBTITLE = (
    "Ključni podatki in kazalniki stanja, stopnje razvoja, vpliva in "
    "učinkovitosti upravljanja turizma"
)
APP_DESCRIPTION = (
    "Preko 100 podatkov in strukturiranih tržnih, poslovnih, ekonomskih, "
    "družbenih in okoljskih kazalnikov za vsako od 5 ravni ožje in širše "
    "zaokroženih turističnih območij: Občine, Vodilne turistične destinacije, "
    "Perspektivne turistične destinacije, Turistične regije, Makro "
    "destinacije in nacionalne ravni slovenskega turizma. Medsebojne "
    "primerjave in konkurenčno uvrščanje posameznih območij, primerjave s "
    "kazalniki na ravni Slovenije. Diagnostika stanja in generiranje "
    "priporočil  o razvoju in delovanju turizma na ravni destinacij. Stalna "
    "nadgradnja z aktualnimi podatki, novimi kazalniki in prikazi, tudi s "
    "pomočjo umetne inteligence."
)
PAGE_TITLE = (
    "Upravljanje turističnih destinacij Slovenije© \n "
    "Ključni podatki in kazalniki"
)
YEAR_NOTE_TEXT = (
    "***Podatki in kazalniki se nanašajo na leto 2024 (v kolikor leto ni "
    "posebej navedeno), leto 2025 in primerjalne podatke z letom 2019 "
    "(posebej označeno)***"
)
FOOTER_SOURCE_TEXT = (
    "Viri podatkov: SURS, AJPES, Narodna Banka Slovenije, Slovenska "
    "Turistična Organizacija, Lastna obdelava, izračuni in dodatne ocene "
    "manjkajočih podatkov - Hosting Management & Consulting d.o.o."
)
FOOTER_AUTHOR_TEXT = (
    "Avtor, izvajalec in skrbnik aplikacije: Hosting Management & Consulting "
    "d.o.o., kontakt: info@hosting.si, tel. +386 (0)41 514 020"
)

DATA_XLSX_FILENAME = "Skupna tabela občine.xlsx"
GEOJSON_FILENAME = "si.json"
MAPPING_XLSX_FILENAME = "mapping.xlsx"
TITLE_FALLBACK_FILENAME = "Title.jpg"
AI_ICON_FILENAME = "AI image.png"
AI_BANNER_FILENAME = "Banner AI analizy.jpg"
FOOTER_LOGO_FILENAME = "footer_logo.jpg"

GROUP_COLOR_EMOJI = {
    "Družbeni kazalniki": "🟦",
    "Okoljski kazalniki": "🟩",
    "Ekonomski nastanitveni in tržni turistični kazalniki": "🟥",
    "Ekonomsko poslovni kazalniki turistične dejavnosti": "🟪",
}

GROUP_BUTTON_IMAGE_FILES = {
    "__all__": "Button - Vsi kazalniki.png",
    "Družbeni kazalniki": "Button - Družbeni kazalniki.png",
    "Okoljski kazalniki": "Button - Okoljski kazalniki.png",
    "Ekonomski nastanitveni in tržni turistični kazalniki": (
        "Button - Ekonomski nastanitveni in tržni turistični kazalniki.png"
    ),
    "Ekonomsko poslovni kazalniki turistične dejavnosti": (
        "Button - Ekonomsko poslovni kazalniki turistične dejavnosti.png"
    ),
}

TOP_BOTTOM_GROUP_LIMITS = {
    "Družbeni kazalniki": 4,
    "Okoljski kazalniki": 3,
    "Ekonomski nastanitveni in tržni turistični kazalniki": 5,
    "Ekonomsko poslovni kazalniki turistične dejavnosti": 5,
}
TOP_BOTTOM_GROUP_ORDER = list(TOP_BOTTOM_GROUP_LIMITS.keys())

SLO_BOUNDS = [[41.00, 10.38], [49.88, 18.61]]

AI_CACHE_CONNECTION_NAME_DEFAULT = "ai_cache_db"
AI_CACHE_TABLE_NAME = "ai_commentary_cache"

MARKET_PREFIX = "Delež vseh prenočitev - "
MARKET_COLOR_MAP = {
    "Domači trg": "#1f77b4",
    "DACH trgi (nemško govoreči trgi: D, A in CH)": "#ff7f0e",
    "Italijanski trg": "#2ca02c",
    "Vzh.evropski trgi (PL,CZ,HU,SK,LIT,LTV,EST,RU,UKR)": "#d62728",
    "Drugi zah.in sev. evropski trgi (ES,P, F,Benelux, Skandinavske države)": "#9467bd",
    "Prekomorski trgi (ZDA, VB, CAN, AU, Azija)": "#17becf",
    "Trgi JV Evrope": "#bcbd22",
    "Vsi drugi tuji trgi": "#7f7f7f",
}

VIEW_CANDIDATES = [
    ("Turistične regije", ["turisticna regija", "turisticne regije"]),
    ("Vodilne destinacije", ["vodilna destinacija", "vodilne destinacije"]),
    ("Makrodestinacije", ["makrodestinacija", "makrodestinacije", "makro destinacije"]),
    ("Regijske destinacije", ["regijska destinacija", "regijske destinacije"]),
    ("Perspektivne destinacije", ["perspektivna destinacija", "perspektivne destinacije"]),
]

AGG_RULES = {
    "Površina območja (km2)": ("sum", None),
    "Število prebivalcev (H2/2024)": ("sum", None),
    "Število prebivalcev (H2/2025)": ("sum", None),
    "Povprečna starost prebivalcev 2024": ("wmean", "Število prebivalcev (H2/2024)"),
    "Povprečna starost prebivalcev 2025": ("wmean", "Število prebivalcev (H2/2025)"),
    "Naravni prirast /1000 prebival.": ("wmean", "Število prebivalcev (H2/2024)"),
    "Selitveni prirast /1000 prebival.": ("wmean", "Število prebivalcev (H2/2024)"),
    "Prenočitve turistov SKUPAJ - 2019": ("sum", None),
    "Prenočitve turistov Domači - 2019": ("sum", None),
    "Prenočitve turistov Tuji - 2019": ("sum", None),
    "Prenočitve turistov SKUPAJ - 2024": ("sum", None),
    "Prenočitve turistov Domači - 2024": ("sum", None),
    "Prenočitve turistov Tuji - 2024": ("sum", None),
    "Prenočitve turistov SKUPAJ - 2025": ("sum", None),
    "Prenočitve turistov Domači - 2025": ("sum", None),
    "Prenočitve turistov Tuji - 2025": ("sum", None),
    "Prenočitve - povprečno število prenočitev na mesec": ("sum", None),
    "Delež tujih prenočitev - 2019": ("wmean", "Prenočitve turistov SKUPAJ - 2019"),
    "Delež tujih prenočitev - 2024": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Delež tujih prenočitev - 2025": ("wmean", "Prenočitve turistov SKUPAJ - 2025"),
    "Rast števila prenočitev 2024/2019 - SKUPAJ": ("wmean", "Prenočitve turistov SKUPAJ - 2019"),
    "Rast števila prenočitev 2024/2019 - Domači": ("wmean", "Prenočitve turistov SKUPAJ - 2019"),
    "Rast števila prenočitev 2024/2019 - Tuji": ("wmean", "Prenočitve turistov SKUPAJ - 2019"),
    "Rast števila prenočitev 2025/2019 - SKUPAJ": ("wmean", "Prenočitve turistov SKUPAJ - 2019"),
    "Rast števila prenočitev 2025/2019 - Domači": ("wmean", "Prenočitve turistov SKUPAJ - 2019"),
    "Rast števila prenočitev 2025/2019 - Tuji": ("wmean", "Prenočitve turistov SKUPAJ - 2019"),
    "Rast števila prenočitev 2025/2024 - SKUPAJ": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Rast števila prenočitev 2025/2024 - Domači": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Rast števila prenočitev 2025/2024 - Tuji": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Prihodi turistov SKUPAJ - 2024": ("sum", None),
    "Prihodi turistov Domači - 2024": ("sum", None),
    "Prihodi turistov Tuji - 2024": ("sum", None),
    "Prihodi turistov SKUPAJ - 2025": ("sum", None),
    "Prihodi turistov Domači - 2025": ("sum", None),
    "Prihodi turistov Tuji - 2025": ("sum", None),
    "PDB turistov SKUPAJ - 2024": ("wmean", "Prihodi turistov SKUPAJ - 2024"),
    "PDB turistov Domači - 2024": ("wmean", "Prihodi turistov Domači - 2024"),
    "PDB turistov Tuji - 2024": ("wmean", "Prihodi turistov Tuji - 2024"),
    "PDB turistov SKUPAJ - 2025": ("wmean", "Prihodi turistov SKUPAJ - 2025"),
    "PDB turistov Domači - 2025": ("wmean", "Prihodi turistov Domači - 2025"),
    "PDB turistov Tuji - 2025": ("wmean", "Prihodi turistov Tuji - 2025"),
    "Nastanitvene kapacitete - Nedeljive enote": ("sum", None),
    "Nastanitvene kapacitete - vsa ležišča": ("sum", None),
    "Nastanitvene kapacitete - stalna ležišča": ("sum", None),
    "Struktura nastanitvenih kapacitet - Sobe (nedeljive enote) - Hoteli in podobni obrati": ("sum", None),
    "Struktura nastanitvenih kapacitet - Sobe (nedeljive enote) - Kampi": ("sum", None),
    "Struktura nastanitvenih kapacitet - Sobe (nedeljive enote) - Druge vrste kapacitet": ("sum", None),
    "Struktura nastanitvenih kapacitet - Stalna ležišča - Hoteli in podobni obrati": ("sum", None),
    "Struktura nastanitvenih kapacitet - Stalna ležišča - Kampi": ("sum", None),
    "Struktura nastanitvenih kapacitet - Stalna ležišča - Druge vrste kapacitet": ("sum", None),
    "Delež stalnih ležišč v Hotelih ipd.": ("wmean", "Nastanitvene kapacitete - stalna ležišča"),
    "Število vseh nastanitvenih obratov 2025": ("sum", None),
    "Nastanitvene kapacitete - Nedeljive enote 2025": ("sum", None),
    "Nastanitvene kapacitete - stalna ležišča 2025": ("sum", None),
    "Število sob (ned.enot) v kapacitetah višje kakovosti - ( 4* in 5*) 2025": ("sum", None),
    "Delež sob (ned.enot) v kapacitetah višje kakovosti - (4* in 5*) 2025": ("wmean", "Nastanitvene kapacitete - Nedeljive enote 2025"),
    "Število hotelov ipd. NO 2025": ("sum", None),
    "Število sob v hotelih ipd. NO 2025": ("sum", None),
    "Število stalnih ležišč v hotelih ipd. NO 2025": ("sum", None),
    "Delež sob (enot) v hotelih ipd. NO 2025": ("wmean", "Nastanitvene kapacitete - Nedeljive enote 2025"),
    "Delež stalnih ležišč v hotelih ipd. NO": ("wmean", "Nastanitvene kapacitete - stalna ležišča 2025"),
    "Število kampov 2025": ("sum", None),
    "Število enot v kampih 2025": ("sum", None),
    "Število ležišč v kampih 2025": ("sum", None),
    "Delež sob (enot) v kampih 2025": ("wmean", "Nastanitvene kapacitete - Nedeljive enote 2025"),
    "Število turističnih kmetij z nastanitvijo 2025": ("sum", None),
    "Število sob v turističnih kmetijah z nastanitvijo 2025": ("sum", None),
    "Število ležišč v turističnih kmetijah z nastanitvijo 2025": ("sum", None),
    "Delež sob (enot) v turističnih kmetijah z nastanitvijo 2025": ("wmean", "Nastanitvene kapacitete - Nedeljive enote 2025"),
    "Število vseh drugih vrst NO 2025": ("sum", None),
    "Število sob v vseh drugih vrstah NO 2025": ("sum", None),
    "Število ležišč v vseh drugih vrstah NO 2025": ("sum", None),
    "Delež sob (enot) v vseh drugih vrstah NO 2025": ("wmean", "Nastanitvene kapacitete - Nedeljive enote 2025"),
    "Povprečna letna zasedenost staln. Ležišč 2024": ("wmean", "Nastanitvene kapacitete - stalna ležišča"),
    "Povprečna letna zasedenost staln. Ležišč 2025": ("wmean", "Nastanitvene kapacitete - stalna ležišča 2025"),
    "Ocenjena povp. Letna zased. sob (nedeljivih enot) 2024": ("wmean", "Nastanitvene kapacitete - Nedeljive enote"),
    "Ocenjena povp. Letna zased. sob (nedeljivih enot) 2025": ("wmean", "Nastanitvene kapacitete - Nedeljive enote 2025"),
    "Pritisk turizma na družbeni prostor (število stalnih ležišč / 100 prebivalcev)": ("wmean", "Število prebivalcev (H2/2024)"),
    "Pritisk turizma na družbeni prostor (število stalnih ležišč / 100 prebivalcev) 2025": ("wmean", "Število prebivalcev (H2/2025)"),
    "Gostota turizma": ("wmean", "Površina območja (km2)"),
    "Gostota turizma 2025": ("wmean", "Površina območja (km2)"),
    "Intenzivnost turizma (število nočitev na dan / 100 prebivalcev)": ("wmean", "Število prebivalcev (H2/2024)"),
    "Intenzivnost turizma (število nočitev na dan / 100 prebivalcev) 2025": ("wmean", "Število prebivalcev (H2/2025)"),
    "Delovno aktivno prebivalstvo v turizmu (OECD/WTO)": ("sum", None),
    "Delovno aktivno prebivalstvo v turizmu (OECD/WTO) 2025": ("sum", None),
    "Število zaposl. in samozaposl. v aktivnih podjetjih v Gostinstvu (I)": ("sum", None),
    "Zaposleni v Gostinstvu (I) v registr.podjetjih in s.p.": ("sum", None),
    "Zaposleni v nastan.dejav. (I55) v registr.podjetjih in s.p.": ("sum", None),
    "Vsi delovni aktivni na območju": ("sum", None),
    "Delež delovno aktivnih od vseh prebivalcev območja": ("wmean", "Število prebivalcev (H2/2024)"),
    "Število prebivalcev starih 15 let ali več na območju": ("sum", None),
    "Število prebivalcev starih 15 let ali več s srednješolsko strokovno ali splošno izobrazbo": ("sum", None),
    "Delež prebivalcev starih 15 let ali več s srednješolsko strokovno ali splošno izobrazbo": ("wmean", "Število prebivalcev (H2/2024)"),
    "Število prebivalcev starih 15 let ali več z izobrazbo višjo od srednješolske": ("sum", None),
    "Delež prebivalcev starih 15 let ali več z izobrazbo višjo od srednješolske": ("wmean", "Število prebivalcev (H2/2024)"),
    "Vsi delovno aktivni na območju 2025": ("sum", None),
    "Delež delovno aktivnih od vseh prebivalcev območja 2025": ("wmean", "Število prebivalcev (H2/2025)"),
    "Delež delovno aktivnih v turizmu (OECD/WTO)": ("wmean", "Vsi delovni aktivni na območju"),
    "Delež delovno aktivnih v turizmu (OECD/WTO) 2025": ("wmean", "Vsi delovno aktivni na območju 2025"),
    "Število vseh vrst podjetij na območju": ("sum", None),
    "Prihodek (v 1000 EUR) vseh podjetij na območju": ("sum", None),
    "Število reg. podjetij in s.p.  v Gostinstvu (I)": ("sum", None),
    "Prihodki reg.podjetij in s.p. v Gostinstvu (I)": ("sum", None),
    "Dodana vrednost reg.podjetij v Gostinstvu (I)": ("sum", None),
    "Dodana vrednost/zaposl. reg.podjetij Gostinstvu (I)": ("wmean", "Zaposleni v Gostinstvu (I) v registr.podjetjih in s.p."),
    "Ocenjeni stroški dela v reg. podj. v Gostinski (I) dejavnosti": ("sum", None),
    "Stroški dela na zaposl. na leto v reg. podj. v Gostinski (I) dejavnosti": ("wmean", "Zaposleni v Gostinstvu (I) v registr.podjetjih in s.p."),
    "Delež stroškov dela v prihodkih v reg. podj. v Gostinstvu (I)": ("wmean", "Prihodki reg.podjetij in s.p. v Gostinstvu (I)"),
    "Delež stroškov dela v dod vredn. v reg. podj. v Gostinstvu (I)": ("wmean", "Dodana vrednost reg.podjetij v Gostinstvu (I)"),
    "EBITDA v reg.podjetjih in s.p. v Gostinstvu (I)": ("sum", None),
    "EBITDA marža v reg.podjetjih in s.p. v Gostinstvu (I)": ("wmean", "Prihodki reg.podjetij in s.p. v Gostinstvu (I)"),
    "Čisti dobiček/izguba v reg. podj. in s.p. v Gostinstvu (I)": ("sum", None),
    "Sredstva v reg. Podjetjih in s.p. v Gostinstvu (I)": ("sum", None),
    "Kapital v reg. Podjetjih in s.p. v Gostinstvu (I)": ("sum", None),
    "Donosnost sredstev v reg. podjetjih in s.p. v Gostinstvu (I)": ("wmean", "Sredstva v reg. Podjetjih in s.p. v Gostinstvu (I)"),
    "Donosnost kapitala v reg. podjetjih in s.p. v Gostinstvu (I)": ("wmean", "Kapital v reg. Podjetjih in s.p. v Gostinstvu (I)"),
    "Dobičkovnost prihodkov v podjetjih in s.p. v Gostinstvu (I)": ("wmean", "Prihodki reg.podjetij in s.p. v Gostinstvu (I)"),
    "Število reg. podjetij in s.p. v nastanitveni dejav. (I 55)": ("sum", None),
    "Prihodki reg.podjetij in s.p. v nastanitveni dejav. (I 55)": ("sum", None),
    "Dodana vrednost reg.podjetij v nastanitveni dejav. (I 55)": ("sum", None),
    "Dodana vrednost/zaposl. V reg.podjetjih v nast.dejav. (I 55)": ("wmean", " Zaposleni v nastan.dejav. (I55) v registr.podjetjih in s.p."),
    "Ocenjeni stroški dela v reg. podj. v nastan.gost. (I 55) dejavnosti": ("sum", None),
    "Stroški dela na zaposl. na leto v reg. podj. v nast.gost. (I 55) dejavnosti": ("wmean", " Zaposleni v nastan.dejav. (I55) v registr.podjetjih in s.p."),
    "Delež stroškov dela v prihodkih v reg. podj. v nast.gost.dej. (I 55)": ("wmean", "Prihodki reg.podjetij in s.p. v nastanitveni dejav. (I 55)"),
    "Delež stroškov dela v dod vredn. v reg. podj. v nast.gost.dej. (I 55)": ("wmean", "Dodana vrednost reg.podjetij v nastanitveni dejav. (I 55)"),
    "EBITDA v reg.podjetjih in s.p. v nastanitveni dejav. (I 55)": ("sum", None),
    "EBITDA marža v reg.podjetjih v nastanitveni dejav. (I 55)": ("wmean", "Prihodki reg.podjetij in s.p. v nastanitveni dejav. (I 55)"),
    "Čisti dobiček/izguba v reg. podj. v nastanitveni dejav. (I 55)": ("sum", None),
    "Sredstva v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)": ("sum", None),
    "Kapital v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)": ("sum", None),
    "Donosnost sredstev v nastanitveni dejav. (I 55)": ("wmean", "Sredstva v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)"),
    "Donosnost kapitala v nastanitveni dejav. (I 55)": ("wmean", "Kapital v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)"),
    "Dobičkovnost prihodkov v nastanitveni dejav. (I 55)": ("wmean", "Prihodki reg.podjetij in s.p. v nastanitveni dejav. (I 55)"),
    "Celotni prihodki v nastan. dejav. na prenočitev": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Ocenjeni prihodki iz nast. dejav. na prenočitev": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Ocenjeni prihodki iz nastan. dej. na razpoložljivo sobo (enoto)": ("wmean", "Nastanitvene kapacitete - Nedeljive enote"),
    "Ocenjeni prihodki iz nast.dej. na prodano sobo (ned.enoto)": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Poraba el.energije (MWh) Dejavnost Gostinstvo (I)": ("sum", None),
    "Poraba el.energije (MWh) Dejavnost Gostinstvo (I) 2025": ("sum", None),
    "Poraba el.energ. v kWh na realiz. 1000 EUR prihodka v Gostinstvu (I)": ("wmean", "Prihodki reg.podjetij in s.p. v Gostinstvu (I)"),
    "Število kmetijskih  gospodarstev": ("sum", None),
    "Ocena skupne ekonomske velikosti kmetij.gospodarstev": ("sum", None),
    "Skupaj neto prejeti dohodek povp. na prebivalca": ("wmean", "Število prebivalcev (H2/2024)"),
    "Neto prejeti dohodek iz dela, povp. na preb.": ("wmean", "Število prebivalcev (H2/2024)"),
    "Neto prejeti dohodek iz premoženja, kapitala, idr.povp. na preb.": ("wmean", "Število prebivalcev (H2/2024)"),
    "Povprečna mesečna neto  plača/zaposl. osebo (EUR)": ("wmean", "Vsi delovni aktivni na območju"),
    "Povprečna mesečna neto  plača/zaposl. osebo (EUR) 2025": ("wmean", "Vsi delovno aktivni na območju 2025"),
    "Povprečna neto plača izplačana na zaposl. osebo v Gostinstvu (I)": ("wmean", "Število zaposl. in samozaposl. v aktivnih podjetjih v Gostinstvu (I)"),
    "Povprečna neto plača izplačana na zaposl. osebo v Gostinstvu (I) 2025": ("wmean", "Število zaposl. in samozaposl. v aktivnih podjetjih v Gostinstvu (I)"),
    "Indeks neto plača v Gostinstvu (I) /pvp. plača v vseh dejavnostih": ("wmean", "Vsi delovni aktivni na območju"),
    "Indeks neto plača v Gostinstvu (I) /pvp. plača v vseh dejavnostih 2025": ("wmean", "Vsi delovno aktivni na območju 2025"),
    "Število izdanih gradbenih dovoljenj/1000 prebivalcev": ("wmean", "Število prebivalcev (H2/2024)"),
    "Število počitniških stanovanj": ("sum", None),
    "Delež naseljenih stanovanj od vseh razp.": ("mean", None),
    "Komunalni odpadki, zbrani  z javnim odvozom (kg/prebivalca)": ("wmean", "Število prebivalcev (H2/2024)"),
    "Štev.dijakov in študentov višjih strok. in visokošolsk.progr./1000 preb.": ("wmean", "Število prebivalcev (H2/2024)"),
    "Število vseh stanovanj": ("sum", None),
    "Delež naseljenih stanovanj": ("wmean", "Število vseh stanovanj"),
    "GINI Indeks - sezonskost prenočitev - 2024": ("wmean", "Prenočitve - povprečno število prenočitev na mesec"),
    "GINI Indeks - sezonskost prenočitev - 2025": ("wmean", "Prenočitve - povprečno število prenočitev na mesec"),
    "Gibanje GINI Indeksa prenoč. 2024/2019": ("wmean", "Prenočitve - povprečno število prenočitev na mesec"),
    "Gibanje GINI Indeksa prenoč. 2025/2019": ("wmean", "Prenočitve - povprečno število prenočitev na mesec"),
    "Delež vseh prenočitev - Domači trg": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Delež vseh prenočitev - DACH trgi (nemško govoreči trgi: D, A in CH)": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Delež vseh prenočitev - Italijanski trg": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Delež vseh prenočitev - Vzh.evropski trgi (PL,CZ,HU,SK,LIT,LTV,EST,RU,UKR)": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Delež vseh prenočitev - Drugi zah.in sev. evropski trgi (ES,P, F,Benelux, Skandinavske države)": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Delež vseh prenočitev - Prekomorski trgi (ZDA, VB, CAN, AU, Azija)": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Delež vseh prenočitev - Trgi JV Evrope": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
    "Delež vseh prenočitev - Vsi drugi tuji trgi": ("wmean", "Prenočitve turistov SKUPAJ - 2024"),
}

TOP_BOTTOM_EXCLUDED_INDICATORS = {
    "Število prebivalcev (H2/2024)",
    "Povprečna starost prebivalcev 2024",
    "Naravni prirast /1000 prebival.",
    "Selitveni prirast /1000 prebival.",
    "Pritisk turizma na družbeni prostor (število stalnih ležišč / 100 prebivalcev)",
    "Delovno aktivno prebivalstvo v turizmu (OECD/WTO)",
    "Vsi delovni aktivni na območju",
    "Delež delovno aktivnih od vseh prebivalcev območja",
    "Število prebivalcev starih 15 let ali več na območju",
    "Število prebivalcev starih 15 let ali več s srednješolsko strokovno ali splošno izobrazbo",
    "Število prebivalcev starih 15 let ali več z izobrazbo višjo od srednješolske",
    "Vsi delovno aktivni na območju 2025",
    "Delež delovno aktivnih v turizmu (OECD/WTO)",
    "Povprečna mesečna neto  plača/zaposl. osebo (EUR)",
    "Povprečna neto plača izplačana na zaposl. osebo v Gostinstvu (I)",
    "Indeks neto plača v Gostinstvu (I) /pvp. plača v vseh dejavnostih",
    "Poraba el.energije (MWh) Dejavnost Gostinstvo (I)",
    "Prenočitve turistov SKUPAJ - 2019",
    "Prenočitve turistov Domači - 2019",
    "Prenočitve turistov Tuji - 2019",
    "Delež tujih prenočitev - 2019",
    "Prenočitve turistov SKUPAJ - 2024",
    "Prenočitve turistov Domači - 2024",
    "Prenočitve turistov Tuji - 2024",
    "GINI Indeks - sezonskost prenočitev - 2024",
    "Rast števila prenočitev 2024/2019 - SKUPAJ",
    "Rast števila prenočitev 2024/2019 - Domači",
    "Rast števila prenočitev 2024/2019 - Tuji",
    "Delež tujih prenočitev - 2024",
    "Delež vseh prenočitev - Domači trg - 2024",
    "Delež vseh prenočitev - DACH trgi (nemško govoreči trgi: D, A in CH) - 2024",
    "Delež vseh prenočitev - Italijanski trg - 2024",
    "Delež vseh prenočitev - Vzh.evropski trgi (PL,CZ,HU,SK,LIT,LTV,EST,RU,UKR) - 2024",
    "Delež vseh prenočitev - Drugi zah.in sev. evropski trgi (ES,P, F,Benelux, Skandinavske države) - 2024",
    "Delež vseh prenočitev - Prekomorski trgi (ZDA, VB, CAN, AU, Azija) - 2024",
    "Delež vseh prenočitev - Trgi JV Evrope - 2024",
    "Delež vseh prenočitev - Vsi drugi tuji trgi - 2024",
    "Prihodi turistov SKUPAJ - 2024",
    "Prihodi turistov Domači - 2024",
    "Prihodi turistov Tuji - 2024",
    "PDB turistov SKUPAJ - 2024",
    "PDB turistov Domači - 2024",
    "PDB turistov Tuji - 2024",
    "Gibanje GINI Indeksa prenoč. 2024/2019",
    "Nastanitvene kapacitete - Nedeljive enote",
    "Nastanitvene kapacitete - vsa ležišča",
    "Nastanitvene kapacitete - stalna ležišča",
    "Struktura nastanitvenih kapacitet - Sobe (nedeljive enote) - Hoteli in podobni obrati",
    "Struktura nastanitvenih kapacitet - Sobe (nedeljive enote) - Kampi",
    "Struktura nastanitvenih kapacitet - Sobe (nedeljive enote) - Druge vrste kapacitet",
    "Struktura nastanitvenih kapacitet - Stalna ležišča - Hoteli in podobni obrati",
    "Struktura nastanitvenih kapacitet - Stalna ležišča - Kampi",
    "Struktura nastanitvenih kapacitet - Stalna ležišča - Druge vrste kapacitet",
    "Delež stalnih ležišč v Hotelih ipd.",
    "Število sob (ned.enot) v kapacitetah višje kakovosti - ( 4* in 5*) 2025",
    "Število sob v hotelih ipd. NO 2025",
    "Število stalnih ležišč v hotelih ipd. NO 2025",
    "Delež stalnih ležišč v hotelih ipd. NO",
    "Število enot v kampih 2025",
    "Število ležišč v kampih 2025",
    "Število sob v turističnih kmetijah z nastanitvijo 2025",
    "Število ležišč v turističnih kmetijah z nastanitvijo 2025",
    "Število sob v vseh drugih vrstah NO 2025",
    "Število ležišč v vseh drugih vrstah NO 2025",
    "Povprečna letna zasedenost staln. Ležišč 2024",
    "Ocenjena povp. Letna zased. sob (nedeljivih enot) 2024",
    "Ocenjeni stroški dela v reg. podj. v Gostinski (I) dejavnosti",
    "Ocenjeni stroški dela v reg. podj. v nastan.gost. (I 55) dejavnosti",
}

INDIKATORJI_Z_INDEKSI = {
    "PDB turistov SKUPAJ - 2024",
    "PDB turistov Domači - 2024",
    "PDB turistov Tuji - 2024",
    "PDB turistov SKUPAJ - 2025",
    "PDB turistov Domači - 2025",
    "PDB turistov Tuji - 2025",
    "GINI Indeks - sezonskost prenočitev - 2024",
    "GINI Indeks - sezonskost prenočitev - 2025",
    "Gibanje GINI Indeksa prenoč. 2025/2019",
    "Gibanje GINI Indeksa prenoč. 2024/2019",
    "Pritisk turizma na družbeni prostor (število stalnih ležišč / 100 prebivalcev)",
    "Pritisk turizma na družbeni prostor (število stalnih ležišč / 100 prebivalcev) 2025",
    "Gostota turizma",
    "Gostota turizma 2025",
    "Intenzivnost turizma (število nočitev na dan / 100 prebivalcev)",
    "Intenzivnost turizma (število nočitev na dan / 100 prebivalcev) 2025",
    "Dodana vrednost/zaposl. reg.podjetij Gostinstvu (I)",
    "Dodana vrednost/zaposl. V reg.podjetjih v nast.dejav. (I 55)",
    "Ocenjeni prihodki iz nast. dejav. na prenočitev",
    "Ocenjeni prihodki iz nastan. dej. na razpoložljivo sobo (enoto)",
    "Poraba el.energ. v kWh na realiz. 1000 EUR prihodka v Gostinstvu (I)",
    "Povprečna starost prebivalcev",
    "Stroški dela na zaposl. na leto v reg. podj. v Gostinski (I) dejavnosti",
    "Dodana vrednost/zaposl. V reg.podjetjih v nast.dejav. (I 55)",
    "Stroški dela na zaposl. na leto v reg. podj. v nast.gost. (I 55) dejavnosti",
    "Celotni prihodki v nastan. dejav. na prenočitev",
    "Ocenjeni prihodki iz nast. dejav. na prenočitev",
    "Ocenjeni prihodki iz nast.dej. na prodano sobo (ned.enoto)",
    "Poraba el.energ. v kWh na realiz. 1000 EUR prihodka v Gostinstvu (I)",
    "Skupaj neto prejeti dohodek povp. na prebivalca",
    "Neto prejeti dohodek iz dela, povp. na preb.",
    "Neto prejeti dohodek iz premoženja, kapitala, idr.povp. na preb.",
    "Povprečna mesečna neto  plača/zaposl. osebo (EUR)",
    "Povprečna mesečna neto  plača/zaposl. osebo (EUR) 2025",
    "Povprečna neto plača izplačana na zaposl. osebo v Gostinstvu (I)",
    "Povprečna neto plača izplačana na zaposl. osebo v Gostinstvu (I) 2025",
}

INDIKATORJI_Z_OPOMBO = {
    "Ekonomsko poslovni kazalniki turistične dejavnosti",
    "Zaposleni v Gostinstvu (I) v registr.podjetjih in s.p.",
    "Zaposleni v nastan.dejav. (I55) v registr.podjetjih in s.p.",
    "Vsi delovni aktivni na območju",
    "Delež delovno aktivnih v turizmu (OECD/WTO)",
    "Število vseh vrst podjetij na območju",
    "Prihodek (v 1000 EUR) vseh podjetij na območju",
    "Število reg. podjetij in s.p.  v Gostinstvu (I)",
    "Prihodki reg.podjetij in s.p. v Gostinstvu (I)",
    "Dodana vrednost reg.podjetij v Gostinstvu (I)",
    "Dodana vrednost/zaposl. reg.podjetij Gostinstvu (I)",
    "Ocenjeni stroški dela v reg. podj. v Gostinski (I) dejavnosti",
    "Stroški dela na zaposl. na leto v reg. podj. v Gostinski (I) dejavnosti",
    "Delež stroškov dela v prihodkih v reg. podj. v Gostinstvu (I)",
    "Delež stroškov dela v dod vredn. v reg. podj. v Gostinstvu (I)",
    "EBITDA v reg.podjetjih in s.p. v Gostinstvu (I)",
    "EBITDA marža v reg.podjetjih in s.p. v Gostinstvu (I)",
    "Čisti dobiček/izguba v reg. podj. in s.p. v Gostinstvu (I)",
    "Sredstva v reg. Podjetjih in s.p. v Gostinstvu (I)",
    "Kapital v reg. Podjetjih in s.p. v Gostinstvu (I)",
    "Donosnost sredstev v reg. podjetjih in s.p. v Gostinstvu (I)",
    "Donosnost kapitala v reg. podjetjih in s.p. v Gostinstvu (I)",
    "Dobičkovnost prihodkov v podjetjih in s.p. v Gostinstvu (I)",
    "Število reg. podjetij in s.p. v nastanitveni dejav. (I 55)",
    "Prihodki reg.podjetij in s.p. v nastanitveni dejav. (I 55)",
    "Dodana vrednost reg.podjetij v nastanitveni dejav. (I 55)",
    "Dodana vrednost/zaposl. V reg.podjetjih v nast.dejav. (I 55)",
    "Ocenjeni stroški dela v reg. podj. v nastan.gost. (I 55) dejavnosti",
    "Stroški dela na zaposl. na leto v reg. podj. v nast.gost. (I 55) dejavnosti",
    "Delež stroškov dela v prihodkih v reg. podj. v nast.gost.dej. (I 55)",
    "Delež stroškov dela v dod vredn. v reg. podj. v nast.gost.dej. (I 55)",
    "EBITDA v reg.podjetjih in s.p. v nastanitveni dejav. (I 55)",
    "EBITDA marža v reg.podjetjih v nastanitveni dejav. (I 55)",
    "Čisti dobiček/izguba v reg. podj. v nastanitveni dejav. (I 55)",
    "Sredstva v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)",
    "Kapital v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)",
    "Donosnost sredstev v nastanitveni dejav. (I 55)",
    "Donosnost kapitala v nastanitveni dejav. (I 55)",
    "Dobičkovnost prihodkov v nastanitveni dejav. (I 55)",
    "Celotni prihodki v nastan. dejav. na prenočitev",
    "Ocenjeni prihodki iz nast. dejav. na prenočitev",
    "Ocenjeni prihodki iz nastan. dej. na razpoložljivo sobo (enoto)",
    "Ocenjeni prihodki iz nast.dej. na prodano sobo (ned.enoto)",
    "Poraba el.energ. v kWh na realiz. 1000 EUR prihodka v Gostinstvu (I)",
}

INDIKATORJI_Z_VALUTO = {
    "Prihodki reg.podjetij in s.p. v Gostinstvu (I)",
    "Dodana vrednost reg.podjetij v Gostinstvu (I)",
    "Dodana vrednost/zaposl. reg.podjetij Gostinstvu (I)",
    "Ocenjeni stroški dela v reg. podj. v Gostinski (I) dejavnosti",
    "Stroški dela na zaposl. na leto v reg. podj. v Gostinski (I) dejavnosti",
    "Povprečna neto plača izplačana na zaposl. osebo v Gostinstvu (I)",
    "Povprečna neto plača izplačana na zaposl. osebo v Gostinstvu (I)2025",
    "EBITDA v reg.podjetjih in s.p. v Gostinstvu (I)",
    "Čisti dobiček/izguba v reg. podj. in s.p. v Gostinstvu (I)",
    "Sredstva v reg. Podjetjih in s.p. v Gostinstvu (I)",
    "Kapital v reg. Podjetjih in s.p. v Gostinstvu (I)",
    "Prihodki reg.podjetij in s.p. v nastanitveni dejav. (I 55)",
    "Dodana vrednost reg.podjetij v nastanitveni dejav. (I 55)",
    "Dodana vrednost/zaposl. V reg.podjetjih v nast.dejav. (I 55)",
    "Ocenjeni stroški dela v reg. podj. v nastan.gost. (I 55) dejavnosti",
    "Stroški dela na zaposl. na leto v reg. podj. v nast.gost. (I 55) dejavnosti",
    "EBITDA v reg.podjetjih in s.p. v nastanitveni dejav. (I 55)",
    "Čisti dobiček/izguba v reg. podj. v nastanitveni dejav. (I 55)",
    "Sredstva v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)",
    "Kapital v reg. Podjetjih in s.p. v nastanitveni dejav. (I 55)",
    "Celotni prihodki v nastan. dejav. na prenočitev",
    "Ocenjeni prihodki iz nast. dejav. na prenočitev",
    "Ocenjeni prihodki iz nastan. dej. na razpoložljivo sobo (enoto)",
    "Ocenjeni prihodki iz nast.dej. na prodano sobo (ned.enoto)",
    "Ocena skupne ekonomske velikosti kmetij.gospodarstev",
    "Skupaj neto prejeti dohodek povp. na prebivalca",
    "Neto prejeti dohodek iz dela, povp. na preb.",
    "Neto prejeti dohodek iz premoženja, kapitala, idr.povp. na preb.",
    "Povprečna mesečna neto  plača/zaposl. osebo (EUR)",
    "Povprečna mesečna neto  plača/zaposl. osebo (EUR) 2025",
}

LOWER_IS_BETTER_INDICATORS = {
    "Povprečna starost prebivalcev 2024",
    "Povprečna starost prebivalcev 2025",
    "Pritisk turizma na družbeni prostor (število stalnih ležišč / 100 prebivalcev)",
    "Pritisk turizma na družbeni prostor (število stalnih ležišč / 100 prebivalcev) 2025",
    "Gostota turizma",
    "Gostota turizma 2025",
    "Intenzivnost turizma (število nočitev na dan / 100 prebivalcev)",
    "Intenzivnost turizma (število nočitev na dan / 100 prebivalcev) 2025",
    "GINI Indeks - sezonskost prenočitev - 2024",
    "GINI Indeks - sezonskost prenočitev - 2025",
    "Gibanje GINI Indeksa prenoč. 2025/2019",
    "Gibanje GINI Indeksa prenoč. 2024/2019",
    "Poraba el.energ. v kWh na realiz. 1000 EUR prihodka v Gostinstvu (I)",
    "Poraba el.energije (MWh) Dejavnost Gostinstvo (I) 2025",
    "Delež stroškov dela v prihodkih v reg. podj. v Gostinstvu (I)",
    "Delež stroškov dela v dod vredn. v reg. podj. v Gostinstvu (I)",
    "Delež stroškov dela v prihodkih v reg. podj. v nast.gost.dej. (I 55)",
    "Delež stroškov dela v dod vredn. v reg. podj. v nast.gost.dej. (I 55)",
    "Število počitniških stanovanj",
}

SKUPNO_OPOZORILO_AGREGACIJA = {
    "type": "warning",
    "title": "Glej opozorilo spodaj glede interpretacije tega kazalnika",
    "text": (
        "Opozorilo oz. razkritje avtorja izračunov kazalnikov: pri izračunih "
        "ekonomskih in poslovnih kazalnikov, pri katerih se kombinirajo "
        "finančni podatki iz bilanc podjetij in s.p. (vir AJPES) in fizični "
        "podatki o številu prenočitev turistov, sob, ležišč ali drugi fizični "
        "podatki o določenih količinah kot so poraba energije v kWh, ipd."
        "(vir: SURS), lahko prihaja do nerealnih oz. delno popačenih "
        "vrednosti v primerih, kjer so sedeži družb, ki realizirajo finančne "
        "kategorije poslovanja v drugih občinah oz. regijah, kot so "
        "realizirane prenočitve oz. registrirana ležišča ali sobe, ki jih "
        "upravljajo in realizirajo določene količinske rezultate. Takšen "
        "primer je recimo: sedež družbe Sava Turizem d.d. je v Ljubljani, "
        "kjer so prikazani prihodki in druge poslovne kategorije te družbe, "
        "medtem, ko so prenočitve, sobe, ležišča, količinska poraba energije, "
        "ipd. prikazani v dejanski občini, kjer delujejo nastanitveni gostinski "
        "obrati v lasti in upravljanju te družbe, ipd.. Prav tako v takšnih "
        "primerih niso prikazane realne poslovno-finančne kategorije, ki jih "
        "realizirajo takšne družbe v občinah oz. regijah, kjer ti učinki "
        "dejansko nastajajo (na območjih, kjer nastajajo učinki so torej "
        "prikazane poslovno-finančne kategorije nižje od realnih), temveč se "
        "pojavljajo v višjih zneskih v enakih kategorijah v občinah oz. "
        "regijah kjer so registrirani sedeži takšnih družb oz. podjetij ali "
        "s.p. (tam pa so torej prikazane finančne kategorije višje od realnih). "
        "Kljub temu je smiselno opazovati te poslovno-finančne kategorije "
        "(ki so edine javno na voljo), ob zavedanju tovrstnega popačenja v "
        "enakih oz. podobnih primerih. Poslovno finančni kazalniki pa se "
        "seveda izravnajo in so realno prikazani na ravni celotne Slovenije."
    ),
}

GINI_CHANGE_2024_2019 = {
    "Slovenska Istra": 102.0,
    "Julijske Alpe": 108.7,
    "Gorenjska": 128.3,
    "Goriško, Vipava, Kras": 117.2,
    "Savinjsko, Celje, Obsotelje in Kozjansko": 112.3,
    "Dolenjska, Bela Krajina in Kočevsko": 99.7,
    "Ljubljana in osrednja Slovenija": 98.2,
    "Štajerska (Maribor, Pohorje, Ptuj)": 98.2,
    "Zgornje Savinjska, Šaleška in Koroška": 117.3,
    "Pomurje": 131.9,
    "Posavje": 89.8,
    "Ankaran": 92.5,
    "Bela Krajina": 107.8,
    "Bled": 108.5,
    "Bohinj": 95.3,
    "Brda": 121.1,
    "Celje": 109.1,
    "Cerklje": 108.5,
    "Cerkno": 104.6,
    "Čatež in Posavje": 89.9,
    "Dobrna": 60.2,
    "Dolenjska ": 76.7,
    "Dolina Soče": 105.7,
    "Idrija": 120.4,
    "Izola": 90.9,
    "Kamnik": 104.5,
    "Kočevsko": 129.6,
    "Koper": 119.4,
    "Koroška": 114.9,
    "Kranj": 182.6,
    "Kranjska Gora": 109.5,
    "Kras": 109.2,
    "Laško": 90.4,
    "Ljubljana": 98.5,
    "Maribor - Pohorje": 92.8,
    "Nova Gorica in Vipavska dolina": 142.1,
    "Podčetrtek": 86.6,
    "Portorož - Piran": 103.5,
    "Ptuj": 99.5,
    "Radovljica": 109.5,
    "Rogaška Slatina": 130.9,
    "Rogla-Pohorje": 95.4,
    "Škofja Loka": 104.0,
    "Velenje - Topolšica": 159.5,
    "Zeleni Kras": 103.7,
    "Zgornja Savinjska dolina": 111.1,
    "Zasavje": 59.4,
    "Dežela pod Karavankami": 109.5,
    "Dežela pod Storžičem-Jezersko": 107.2,
    "Dežela suhe robe": 121.6,
    "Haloze": 103.1,
    "Jeruzalem - Ormož": 177.7,
    "Dolina Voglajne": 107.2,
    "Spodnja Savinjska Dolina": 92.8,
    "Alpska Slovenija": 110.3,
    "Mediteranska Slovenija": 104.4,
    "Osrednja Slovenija in Ljubljana": 101.5,
    "Termalna panonska Slovenija": 105.7,
}

GINI_2025_VALUES = {
    "Slovenska Istra": 0.3764876496411522,
    "Julijske Alpe": 0.4452252370330385,
    "Gorenjska": 0.324787552694939,
    "Goriško, Vipava, Kras": 0.3414449949424754,
    "Savinjsko, Celje, Obsotelje in Kozjansko": 0.1055199517632115,
    "Dolenjska, Bela Krajina in Kočevsko": 0.21124381463520803,
    "Ljubljana in osrednja Slovenija": 0.23523946737768442,
    "Štajerska (Maribor, Pohorje, Ptuj)": 0.145742716311569,
    "Zgornje Savinjska, Šaleška in Koroška": 0.32694317150645247,
    "Pomurje": 0.13403248647190102,
    "Posavje": 0.23229533347200115,
    "Ankaran": 0.4357100234542697,
    "Bela Krajina": 0.49020975251494125,
    "Bled": 0.3785475744949536,
    "Bohinj": 0.4385352632723508,
    "Brda": 0.4241196241692765,
    "Celje": 0.13992582342435111,
    "Cerklje": 0.2876691696968393,
    "Cerkno": 0.31919275123558477,
    "Čatež in Posavje": 0.23229533347200115,
    "Dobrna": 0.05329213827211854,
    "Dolenjska ": 0.1276364275442664,
    "Dolina Soče": 0.6111132181663749,
    "Idrija": 0.3037915445201851,
    "Izola": 0.39217616699426416,
    "Kamnik": 0.40680442604879463,
    "Kočevsko": 0.2750451151982596,
    "Koper": 0.4840011412545189,
    "Koroška": 0.2408271237963142,
    "Kranj": 0.2472390007857861,
    "Kranjska Gora": 0.31810803618508043,
    "Kras": 0.32721589471019985,
    "Laško": 0.08005493853615064,
    "Ljubljana": 0.23109570701222903,
    "Maribor - Pohorje": 0.1362495454695022,
    "Nova Gorica in Vipavska dolina": 0.2547356691501057,
    "Podčetrtek": 0.11699362319358553,
    "Portorož - Piran": 0.34168165678568696,
    "Ptuj": 0.2591979023329253,
    "Radovljica": 0.6448870066592807,
    "Rogaška Slatina": 0.09465496429016551,
    "Rogla-Pohorje": 0.2435891574652148,
    "Škofja Loka": 0.422940747435654,
    "Velenje - Topolšica": 0.19122149799355148,
    "Zeleni Kras": 0.4365909696026986,
    "Zgornja Savinjska dolina": 0.5523832496044765,
    "Zasavje": 0.1335160562942227,
    "Dežela pod Karavankami": 0.4795796579337286,
    "Dežela pod Storžičem-Jezersko": 0.5119221497708111,
    "Dežela suhe robe": 0.3336629312239068,
    "Haloze": 0.40572149616420394,
    "Jeruzalem - Ormož": 0.3480701561177296,
    "Dolina Voglajne": 0.40829511876768687,
    "Spodnja Savinjska Dolina": 0.2996528610541874,
    "Alpska Slovenija": 0.3823581168367557,
    "Mediteranska Slovenija": 0.3692930910480988,
    "Osrednja Slovenija in Ljubljana": 0.244510198775449,
    "Termalna panonska Slovenija": 0.15291999846843807,
}

GINI_CHANGE_2025_2019 = {
    "Slovenska Istra": 100.35428320601302,
    "Julijske Alpe": 109.08183907036356,
    "Gorenjska": 138.17761836782358,
    "Goriško, Vipava, Kras": 123.93983073505606,
    "Savinjsko, Celje, Obsotelje in Kozjansko": 114.17358932883543,
    "Dolenjska, Bela Krajina in Kočevsko": 99.37950296201717,
    "Ljubljana in osrednja Slovenija": 101.78732335827748,
    "Štajerska (Maribor, Pohorje, Ptuj)": 98.6291836773505,
    "Zgornje Savinjska, Šaleška in Koroška": 119.0771350171818,
    "Pomurje": 138.7309133821649,
    "Posavje": 97.76073149648599,
    "Ankaran": 92.35218855377471,
    "Bela Krajina": 105.13300231802984,
    "Bled": 108.46566568560738,
    "Bohinj": 96.67032584341408,
    "Brda": 116.76433083357014,
    "Celje": 88.92045230642707,
    "Cerklje": 115.10301046968338,
    "Cerkno": 97.0137628745858,
    "Čatež in Posavje": 97.76073149648599,
    "Dobrna": 67.0382724607493,
    "Dolenjska ": 86.48870644335027,
    "Dolina Soče": 103.28052563675041,
    "Idrija": 144.1640208841851,
    "Izola": 91.44066982231449,
    "Kamnik": 118.58559806455222,
    "Kočevsko": 128.71788046244959,
    "Koper": 122.80266415850882,
    "Koroška": 109.48199553659683,
    "Kranj": 205.79402855354454,
    "Kranjska Gora": 104.28209053110457,
    "Kras": 118.20650808896198,
    "Laško": 92.35427301207905,
    "Ljubljana": 101.4617842164609,
    "Maribor - Pohorje": 98.977665016376,
    "Nova Gorica in Vipavska dolina": 159.02226833306662,
    "Podčetrtek": 98.58677797312706,
    "Portorož - Piran": 99.60928607460905,
    "Ptuj": 113.5872700037615,
    "Radovljica": 108.6934513206192,
    "Rogaška Slatina": 119.07019480894918,
    "Rogla-Pohorje": 90.5254248526441,
    "Škofja Loka": 108.468867299028,
    "Velenje - Topolšica": 155.86505353942923,
    "Zeleni Kras": 108.03087528956112,
    "Zgornja Savinjska dolina": 107.84809907090667,
    "Zasavje": 63.29069475254023,
    "Dežela pod Karavankami": 106.71978301292395,
    "Dežela pod Storžičem-Jezersko": 105.14079772808469,
    "Dežela suhe robe": 113.50082182405778,
    "Haloze": 104.65038871299363,
    "Jeruzalem - Ormož": 187.31875729086752,
    "Dolina Voglajne": 123.86607553639335,
    "Spodnja Savinjska Dolina": 94.98662017366016,
    "Alpska Slovenija": 0.3823581168367557,
    "Mediteranska Slovenija": 0.3692930910480988,
    "Osrednja Slovenija in Ljubljana": 0.244510198775449,
    "Termalna panonska Slovenija": 0.15291999846843807,
}
